name: PX919env
channels:
- conda-forge
- rdkit
- nodefaults
dependencies:
- python
- pip
- ipykernel
- matplotlib
- numpy<2.0.0
- scipy
- ipywidgets
- ipympl
- nodejs
- rdkit
- nglview
- ase
- psi4
- conda-forge/label/libint_dev::libint
- dftd3-python
- resp
- debtcollector
- py3dmol
