name: PX919env
channels:
- psi4
- rdkit
- conda-forge
- defaults
dependencies:
- ipykernel
- matplotlib
- numpy
- scipy
- ipywidgets
- rdkit
- nglview
- ase
- psi4
- resp
- debtcollector
- pip:
  - git+https://github.com/Mishima-syk/psikit.git
- py3dmol
