name: PX919env
channels:
- psi4
- rdkit
- conda-forge
- defaults
dependencies:
- ipykernel
- matplotlib
- numpy
- scipy
- bokeh
- ipywidgets
- rdkit
- mdtraj
- nglview
- ase
- psi4
- resp
- debtcollector
- pip:
  - "--editable=git+https://github.com/Mishima-syk/psikit"
- py3dmol
